INSERT INTO chain_alias_map (protocol, network_slug, argocd_application, argocd_namespace, is_primary)
VALUES
  ('Aelf', 'aelf-mainnet', 'aelf-mainnet', 'chain', TRUE),
  ('Aptos', 'apt-mainnet', 'apt-mainnet', 'chain', TRUE),
  ('Arbitrum', 'arb-mainnet', 'arb-mainnet', 'chain', TRUE),
  ('Avalanche', 'avax-mainnet', 'avax-mainnet', 'chain', TRUE),
  ('Base', 'base-mainnet', 'base-mainnet', 'chain', TRUE),
  ('Bitcoin', 'btc-mainnet', 'btc-mainnet', 'chain', TRUE),
  ('Bitcoin Cash', 'bch-mainnet', 'bch-mainnet', 'chain', TRUE),
  ('BNB Chain', 'bnb-mainnet', 'bnb-mainnet', 'chain', TRUE),
  ('Chiliz', 'chz-mainnet', 'chz-mainnet', 'chain', TRUE),
  ('Dogecoin', 'doge-mainnet', 'doge-mainnet', 'chain', TRUE),
  ('ETC', 'etc-mainnet', 'etc-mainnet', 'chain', TRUE),
  ('Ethereum(Geth-EL)', 'eth-mainnet', 'eth-mainnet', 'chain', TRUE),
  ('Ethereum(Reth-EL)', 'eth-mainnet', 'eth-mainnet', 'chain', TRUE),
  ('Ethereum(Lighthouse-CL)', 'eth-mainnet', 'eth-mainnet', 'chain', TRUE),
  ('Filecoin', 'fil-mainnet', 'fil-mainnet', 'chain', TRUE),
  ('Flow(Access)', 'flow-mainnet', 'flow-mainnet', 'chain', TRUE),
  ('Flow(Consensus)', 'flow-mainnet', 'flow-mainnet', 'chain', TRUE),
  ('Flow(Execution)', 'flow-mainnet', 'flow-mainnet', 'chain', TRUE),
  ('Giwa', 'giwa-sepolia', 'giwa-sepolia', 'chain', TRUE),
  ('Kaia (Klaytn)', 'kaia-mainnet', 'kaia-mainnet', 'chain', TRUE),
  ('Optimism', 'op-mainnet', 'op-mainnet', 'chain', TRUE),
  ('Pocket', 'pokt-mainnet', 'pokt-mainnet', 'chain', TRUE),
  ('Polygon(Bor-EL)', 'pol-mainnet', 'pol-mainnet', 'chain', TRUE),
  ('Polygon(Erigon-EL)', 'pol-mainnet', 'pol-mainnet', 'chain', TRUE),
  ('Polygon(Heimdall-CL)', 'pol-mainnet', 'pol-mainnet', 'chain', TRUE),
  ('Solana(Agave)', 'sol-mainnet', 'sol-mainnet', 'chain', TRUE),
  ('Solana(Jito)', 'sol-mainnet', 'sol-mainnet', 'chain', TRUE),
  ('Sui', 'sui-mainnet', 'sui-mainnet', 'chain', TRUE),
  ('TRON', 'trx-mainnet', 'trx-mainnet', 'chain', TRUE),
  ('ThunderCore', 'tt-mainnet', 'tt-mainnet', 'chain', TRUE),
  ('XRP', 'xrp-mainnet', 'xrp-mainnet', 'chain', TRUE),
  ('ZetaChain', 'zeta-mainnet', 'zeta-mainnet', 'chain', TRUE)
ON CONFLICT (protocol, network_slug) DO NOTHING;
